import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LocalFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const Vazirmatn = LocalFont({
	src: "../public/fonts/Vazirmatn-Regular.woff2",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`bg-white text-slate-950  ${Vazirmatn.className}`}>
        {/* center box */}
        <div className="w-full flex justify-center items-center">
          <div className="lg:w-4/12 md:w-7/12 w-full bg-red-300">
          {children}
          </div>
        </div>
			</body>
		</html>
	);
}

/* import type { Metadata } from "next";
import "./globals.css";
import LocalFont from 'next/font/local'
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Vazirmatn = LocalFont(
  {
    src:"../public/fonts/Vazirmatn-Medium.ttf"
  }
)
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-white text-slate-950 w-full flex justify-center p-2 ${Vazirmatn.className}`}>
      <div className="flex flex-col h-full mx-auto w-full max-w-md relative bg-white">
        {children}
      </div>
      </body>
    </html>
  );
}
 */
