import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LocalFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const Yekan = LocalFont({
	src: "../public/fonts/Yekan.woff",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body dir="rtl"  className={`bg-white text-slate-950  ${Yekan.className}`}>
        {/* center box */}
        <div className="w-full flex justify-center items-center">
          <div className="lg:w-4/12 md:w-7/12 w-full">
          {children}
          </div>
        </div>
			</body>
		</html>
	);
}
